spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/ShiBaSuiGaoJiGongChengShi/config-repo
          username: 756593585@qq.com
          password: talent@123123
          basedir: D:\git
  rabbitmq:
    host: 192.168.1.103
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"